title:       "数据手册"
email:       your-email@example.com
description: A handbook to game data.
baseurl:     ""
url:         ""
logo:        "assets/logo.png" 
separater:   " - "

collections:
  games:
    output: true
    permalink: :path/
  common:
    output: true
    permalink: common/:path/
    
defaults:
  -
    scope:
      path: ""
      type: "games"
    values:
      layout: "gamepage"
  -
    scope:
      path: ""
      type: "common"
    values:
      layout: "page"

  
# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
